apiVersion: apps/v1
kind: Deployment
metadata:
  name: {? {include "nginx-chart.name" .: ''} : ''}
  labels:
    app: {? {include "nginx-chart.name" .: ''} : ''}
spec:
  replicas: {? {.Values.replicaCount: ''} : ''}
  selector:
    matchLabels:
      app: {? {include "nginx-chart.name" .: ''} : ''}
  template:
    metadata:
      labels:
        app: {? {include "nginx-chart.name" .: ''} : ''}
    spec:
      containers:
      - name: {? {.Chart.Name: ''} : ''}
        # image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {? {.Values.image.pullPolicy: ''} : ''}
        ports:
        - name: http
          containerPort: 80
