apiVersion: v1
kind: Service
metadata:
  name: {? {.Values.service.name: ''} : ''}
  labels:
    app: {? {include "nginx-chart.name" .: ''} : ''}
spec:
  type: {? {.Values.service.type: ''} : ''}
  ports:
  - port: {? {.Values.service.port: ''} : ''}
    targetPort: 80
  selector:
    app: {? {include "nginx-chart.name" .: ''} : ''}
